added new modals
damiantchorzewski/Filmoteka-HiFiveTeam pull request #31
Opened 2023-04-19 04:11 UTC by FVuk

- added modal-window (still doesn't work for some reason, plase run code review)
- added modal-team (only need to add our photos/avatars and LI pages)
- removed some unused features
- cleaned up refs.js, local-storage.js and index.js

2023-04-19 14:29 UTC, benbrzezinski requested changes
Tak ogólnie to:
- nazwy plików js miały nazwy camelCase, czyli np. zamiast local-storage -> localStorage 
- modal z nami fajnie działa, a do kart z filmami, sugestia - osobiście użył bym biblioteki np. basiclightbox jak i tak mamy ją zainstalowaną przez npm, trzymałbym się dokumentacji i na podstawie tego napisał funkcję, te małe funkcję dałbym do innego modułu i importował do głównej funkcji

2023-04-19 14:29 UTC, benbrzezinski commented on src/js/index.js
> +import './renderMovieCards.js';
Nie chcemy wszystkiego tak importować bo większość skryptów działa niezależnie od głównego pliku tylko są funkcjami pomocniczymi do większych funkcji, które np. trzeba tylko wywołać bo jak zobaczysz to znikła paginacja ze strony

2023-04-19 14:29 UTC, benbrzezinski commented on src/js/local-storage.js
>  export const queue = getQueueLocalStorage() || [];
Jak już zmieniłeś nazwy funkcji w localStorage to te dwie zostały bez zmian i wywalają undefined

2023-04-19 14:29 UTC, benbrzezinski commented on src/js/api.js
> +export const API_KEY_IMG = `https://image.tmdb.org/t/p/original`;
Takie coś nie robimy można to dorzucić do modułu Api (lub zrobić to bez zmiennej dać ten url do template string) ale nie jako oddzielny export, ponieważ jak użyłeś dalej w kodzie takie coś `Api.API_KEY_IMG` to to nie zadziała jak zrobisz console.log tego to wywali undefined

2023-04-19 14:29 UTC, benbrzezinski commented on src/js/modal-window.js
> +            Api.API_KEY_IMG
To właśnie wywali undefined

2023-04-19 14:29 UTC, benbrzezinski commented on src/sass/utils/_visually-hidden.scss
> -  pointer-events: none;
Tu taka mała uwaga tą klasę wykorzystywała funkcja dla loader jak i svg właśnie loader, który też miał transition opacity ustawione, którego teraz nie ma. Jeśli z jakiegoś powodu potrzebujesz kolejną klasę, która w inny sposób coś znika niż po prostu opacity to dodaj kolejną pod inną nazwą jak np.
.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  padding: 0;
  overflow: hidden;
  white-space: nowrap;
  border: 0;
  clip: rect(0 0 0 0);
  clip-path: inset(50%);
}

2023-04-19 14:29 UTC, benbrzezinski commented on src/sass/utils/_modal-window.scss
> +modal__info-thumb {
Brakuje kropki w klasie

2023-04-19 14:29 UTC, benbrzezinski commented on src/sass/utils/_modal-window.scss
> +.modal__poster {
Brak przerwy

2023-04-19 19:18 UTC, FVuk commented on src/js/index.js
> +import './renderMovieCards.js';
naprawione, dodałem tylko modalTeam a rezta cofnąłem tak jak było więc paginacja znowu działa

2023-04-19 19:19 UTC, FVuk commented on src/js/local-storage.js
>  export const queue = getQueueLocalStorage() || [];
poprawiłem wszystkie nazwy plików js na camelCase także zostawiam tylko kwestie modalWindow

2023-04-19 19:19 UTC, FVuk commented on src/js/api.js
> +export const API_KEY_IMG = `https://image.tmdb.org/t/p/original`;
dodałem do Api

2023-04-19 19:20 UTC, FVuk commented on src/sass/utils/_visually-hidden.scss
> -  pointer-events: none;
specjalnie sprawdzalem ale nie zauważyłem ze loader z tego korzysta. W kazdym razie podmieniłem klasy. is-hidden wykorzystuje modalTeam a .visually-hidden loader także wszystko działa

2023-04-19 19:21 UTC, FVuk commented on src/sass/utils/_modal-window.scss
> +modal__info-thumb {
fixed

2023-04-19 19:21 UTC, FVuk commented on src/sass/utils/_modal-window.scss
> +.modal__poster {
fixed

2023-04-20 08:52 UTC, benbrzezinski approved these changes

2023-04-20 08:56 UTC, merged